export const enDic = {
  'tag.title'                                             : 'jbChess',
  'view.common.yes'                                       : 'Yes',
  'view.common.no'                                        : 'No',
  'view.common.ok'                                        : 'Ok',
  'view.common.cancel'                                    : 'Cancel',
  'view.common.username'                                  : 'Username',
  'view.common.email'                                     : 'Email',
  'view.common.password'                                  : 'Password',
  'view.common.repeat_password'                           : 'Repeat Password',
  'view.common.invalid_value'                             : 'Invalid value',
  'view.common.required_field'                            : 'Required field',
  'view.common.logout'                                    : 'Log Out',
  'scripts.common.oauth.interceptor.connection_error'     : 'Error',
  'scripts.common.oauth.interceptor.forbidden'            : 'Forbidden',
  'scripts.common.oauth.interceptor.internal_server_error': 'Internal Error',
  'scripts.common.oauth.interceptor.service_unavailable'  : 'Service Unavailable',
  'scripts.common.oauth.interceptor.bad_request_error'    : 'Bad Request',
  'views.page-not-found.title'                            : 'Page Not Found',
  'views.page-not-found.message'                          : 'Sorry, it seems this page does not exist',
  'view.sign.email_tip'                                   : 'Please provide a valid email address. A verification with a confirmation will be sent through to activate your new account. This will be your user ID to login into the app.',
  'view.sign.sent_msg'                                    : 'A verification link has been sent to your email address. Please use it to finish your account activation',
  'page.label.login'                                      : 'Login',
  'page.label.home'                                       : 'Home',
  'view.login.text'                                       : 'Login',
  'view.login.log_in_btn'                                 : 'Login',
  'view.login.reset_forgotten_password'                   : 'Forgot Password?',
  'view.login.new_user'                                   : 'Sign in (new user)',
  'view.login.sign_in'                                    : 'Sign In',
  'view.repeat_password'                                  : 'Repeat Password',
  'view.login.user_not_activated'                         : 'Please, use the link on the email to activate your account',
  'view.profile.title'                                    : 'Profile',
  'view.profile.update'                                   : 'Update',
  'view.profile.display_name'                             : 'Display Name',
  'view.profile.updated_successfully'                     : 'Profile updated successfully',
  'view.profile.confirm_logout'                           : 'Do you want to log out?',
};
